markdown: redcarpet
rdiscount:
  extensions: [smart]
timezone: DE


redcarpet:
  syntax_highlighter: rouge


gems:
  - jekyll-sitemap

permalink: /:title


author: Matthias Günther
email: "&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#109;&#97;&#116;&#116;&#104;&#105;&#97;&#115;&#64;&#112;&#97;&#100;&#114;&#105;&#110;&#111;&#98;&#111;&#111;&#107;&#46;&#99;&#111;&#109;"
twitter: https://twitter.com/padrinobook
url: https://padrinobook.com
title: PadrinoBook
description: PadrinoBook - The Guide To Master The Elegant Ruby Web Framework


exclude:
- Gemfile
- Gemfile.lock
- Rakefile
- tags


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
