markdown: redcarpet
highlighter: pygments
rdiscount:
  extensions: [smart]
timezone: DE


permalink: /:title


author: Matthias Günther


exclude:
- Gemfile
- Gemfile.lock
- Rakefile


# yaml default setup
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
